### ISSUE TITLE
contextvars only standard in python 3.7+

### ISSUE THREAD

**Issue by tim-xoi** [xoeye/xoto3#24]
The xoto3 `setup.py` says `>=3.6` for python versions, but in places use the `contextvars` library, which is only standard starting in 3.7. This means 3.6 users will need to install https://pypi.org/project/contextvars/ separately.

**Comment by petergaultney** [comment]
okay, we changed this to say 3.7+. I think there should be a way to dynamically require the backport if installed on 3.6, and we'd certainly accept a PR to do that, but I'm going to close this for now.
